/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StorageMappingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deleteValue"
      | "deleteValueFor"
      | "getAddressCount"
      | "getAllAddresses"
      | "getBatchValues"
      | "getContractInfo"
      | "getValue"
      | "getValueFor"
      | "hasValue"
      | "setValue"
      | "setValueFor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ValueDeleted" | "ValueStored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deleteValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deleteValueFor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchValues",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getValue", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getValueFor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasValue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setValue", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setValueFor",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "deleteValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteValueFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getValue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getValueFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setValue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setValueFor",
    data: BytesLike
  ): Result;
}

export namespace ValueDeletedEvent {
  export type InputTuple = [
    key: AddressLike,
    value: string,
    deletedBy: AddressLike
  ];
  export type OutputTuple = [key: string, value: string, deletedBy: string];
  export interface OutputObject {
    key: string;
    value: string;
    deletedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueStoredEvent {
  export type InputTuple = [
    key: AddressLike,
    value: string,
    storedBy: AddressLike
  ];
  export type OutputTuple = [key: string, value: string, storedBy: string];
  export interface OutputObject {
    key: string;
    value: string;
    storedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StorageMapping extends BaseContract {
  connect(runner?: ContractRunner | null): StorageMapping;
  waitForDeployment(): Promise<this>;

  interface: StorageMappingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deleteValue: TypedContractMethod<[], [void], "nonpayable">;

  deleteValueFor: TypedContractMethod<[key: AddressLike], [void], "nonpayable">;

  getAddressCount: TypedContractMethod<[], [bigint], "view">;

  getAllAddresses: TypedContractMethod<[], [string[]], "view">;

  getBatchValues: TypedContractMethod<
    [keys: AddressLike[]],
    [string[]],
    "view"
  >;

  getContractInfo: TypedContractMethod<[], [[string, bigint]], "view">;

  getValue: TypedContractMethod<[], [string], "view">;

  getValueFor: TypedContractMethod<[key: AddressLike], [string], "view">;

  hasValue: TypedContractMethod<[key: AddressLike], [boolean], "view">;

  setValue: TypedContractMethod<[value: string], [void], "nonpayable">;

  setValueFor: TypedContractMethod<
    [key: AddressLike, value: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deleteValue"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteValueFor"
  ): TypedContractMethod<[key: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAddressCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBatchValues"
  ): TypedContractMethod<[keys: AddressLike[]], [string[]], "view">;
  getFunction(
    nameOrSignature: "getContractInfo"
  ): TypedContractMethod<[], [[string, bigint]], "view">;
  getFunction(
    nameOrSignature: "getValue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getValueFor"
  ): TypedContractMethod<[key: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasValue"
  ): TypedContractMethod<[key: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setValue"
  ): TypedContractMethod<[value: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setValueFor"
  ): TypedContractMethod<
    [key: AddressLike, value: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ValueDeleted"
  ): TypedContractEvent<
    ValueDeletedEvent.InputTuple,
    ValueDeletedEvent.OutputTuple,
    ValueDeletedEvent.OutputObject
  >;
  getEvent(
    key: "ValueStored"
  ): TypedContractEvent<
    ValueStoredEvent.InputTuple,
    ValueStoredEvent.OutputTuple,
    ValueStoredEvent.OutputObject
  >;

  filters: {
    "ValueDeleted(address,string,address)": TypedContractEvent<
      ValueDeletedEvent.InputTuple,
      ValueDeletedEvent.OutputTuple,
      ValueDeletedEvent.OutputObject
    >;
    ValueDeleted: TypedContractEvent<
      ValueDeletedEvent.InputTuple,
      ValueDeletedEvent.OutputTuple,
      ValueDeletedEvent.OutputObject
    >;

    "ValueStored(address,string,address)": TypedContractEvent<
      ValueStoredEvent.InputTuple,
      ValueStoredEvent.OutputTuple,
      ValueStoredEvent.OutputObject
    >;
    ValueStored: TypedContractEvent<
      ValueStoredEvent.InputTuple,
      ValueStoredEvent.OutputTuple,
      ValueStoredEvent.OutputObject
    >;
  };
}
