/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StorageArrayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addValue"
      | "clearAll"
      | "getAllValues"
      | "getContractInfo"
      | "getLength"
      | "getValue"
      | "indexOf"
      | "removeLastValue"
      | "updateValue"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ValueAdded" | "ValueRemoved" | "ValueUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "addValue", values: [string]): string;
  encodeFunctionData(functionFragment: "clearAll", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllValues",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getLength", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "indexOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "removeLastValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateValue",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "addValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "clearAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLength", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "indexOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLastValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateValue",
    data: BytesLike
  ): Result;
}

export namespace ValueAddedEvent {
  export type InputTuple = [
    value: string,
    index: BigNumberish,
    addedBy: AddressLike
  ];
  export type OutputTuple = [value: string, index: bigint, addedBy: string];
  export interface OutputObject {
    value: string;
    index: bigint;
    addedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueRemovedEvent {
  export type InputTuple = [
    value: string,
    index: BigNumberish,
    removedBy: AddressLike
  ];
  export type OutputTuple = [value: string, index: bigint, removedBy: string];
  export interface OutputObject {
    value: string;
    index: bigint;
    removedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueUpdatedEvent {
  export type InputTuple = [
    oldValue: string,
    newValue: string,
    index: BigNumberish,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    oldValue: string,
    newValue: string,
    index: bigint,
    updatedBy: string
  ];
  export interface OutputObject {
    oldValue: string;
    newValue: string;
    index: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StorageArray extends BaseContract {
  connect(runner?: ContractRunner | null): StorageArray;
  waitForDeployment(): Promise<this>;

  interface: StorageArrayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addValue: TypedContractMethod<[value: string], [void], "nonpayable">;

  clearAll: TypedContractMethod<[], [void], "nonpayable">;

  getAllValues: TypedContractMethod<[], [string[]], "view">;

  getContractInfo: TypedContractMethod<[], [[string, bigint]], "view">;

  getLength: TypedContractMethod<[], [bigint], "view">;

  getValue: TypedContractMethod<[index: BigNumberish], [string], "view">;

  indexOf: TypedContractMethod<[value: string], [bigint], "view">;

  removeLastValue: TypedContractMethod<[], [string], "nonpayable">;

  updateValue: TypedContractMethod<
    [index: BigNumberish, newValue: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addValue"
  ): TypedContractMethod<[value: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clearAll"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllValues"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getContractInfo"
  ): TypedContractMethod<[], [[string, bigint]], "view">;
  getFunction(
    nameOrSignature: "getLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValue"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "indexOf"
  ): TypedContractMethod<[value: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeLastValue"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "updateValue"
  ): TypedContractMethod<
    [index: BigNumberish, newValue: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ValueAdded"
  ): TypedContractEvent<
    ValueAddedEvent.InputTuple,
    ValueAddedEvent.OutputTuple,
    ValueAddedEvent.OutputObject
  >;
  getEvent(
    key: "ValueRemoved"
  ): TypedContractEvent<
    ValueRemovedEvent.InputTuple,
    ValueRemovedEvent.OutputTuple,
    ValueRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ValueUpdated"
  ): TypedContractEvent<
    ValueUpdatedEvent.InputTuple,
    ValueUpdatedEvent.OutputTuple,
    ValueUpdatedEvent.OutputObject
  >;

  filters: {
    "ValueAdded(string,uint256,address)": TypedContractEvent<
      ValueAddedEvent.InputTuple,
      ValueAddedEvent.OutputTuple,
      ValueAddedEvent.OutputObject
    >;
    ValueAdded: TypedContractEvent<
      ValueAddedEvent.InputTuple,
      ValueAddedEvent.OutputTuple,
      ValueAddedEvent.OutputObject
    >;

    "ValueRemoved(string,uint256,address)": TypedContractEvent<
      ValueRemovedEvent.InputTuple,
      ValueRemovedEvent.OutputTuple,
      ValueRemovedEvent.OutputObject
    >;
    ValueRemoved: TypedContractEvent<
      ValueRemovedEvent.InputTuple,
      ValueRemovedEvent.OutputTuple,
      ValueRemovedEvent.OutputObject
    >;

    "ValueUpdated(string,string,uint256,address)": TypedContractEvent<
      ValueUpdatedEvent.InputTuple,
      ValueUpdatedEvent.OutputTuple,
      ValueUpdatedEvent.OutputObject
    >;
    ValueUpdated: TypedContractEvent<
      ValueUpdatedEvent.InputTuple,
      ValueUpdatedEvent.OutputTuple,
      ValueUpdatedEvent.OutputObject
    >;
  };
}
